---
abstract: unknown
author:
  - unknown
build_requires:
  Compress::Zlib: 0
  Mojolicious: 2.98
  XML::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rex-IO-Server
no_index:
  directory:
    - t
    - inc
requires:
  Compress::Zlib: 0
  Mojolicious: 2.98
  Rex::IO::CMDB: 0
  XML::Simple: 0
resources:
  repository: https://github.com/krimdomu/rex-io-server
version: v0.0.2
